// user
export const START_FETCHING_USER = 'START_FETCHING_USER'
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS'
export const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE'

// forum
export const START_FETCHING_FORUMS = 'START_FETCHING_FORUMS'
export const STOP_FETCHING_FORUMS = 'STOP_FETCHING_FORUMS'
export const FETCHING_FORUMS_SUCCESS = 'FETCHING_FORUMS_SUCCESS'
export const FETCHING_FORUMS_FAILURE = 'FETCHING_FORUMS_FAILURE'
export const UPDATE_CURRENT_FORUM = 'UPDATE_CURRENT_FORUM'
