// user
export const START_FETCHING_USER = 'START_FETCHING_USER'
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS'
export const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE'

// forum
export const START_FETCHING_FORUMS = 'START_FETCHING_FORUMS'
export const STOP_FETCHING_FORUMS = 'STOP_FETCHING_FORUMS'
export const FETCHING_FORUMS_SUCCESS = 'FETCHING_FORUMS_SUCCESS'
export const FETCHING_FORUMS_FAILURE = 'FETCHING_FORUMS_FAILURE'
export const UPDATE_CURRENT_FORUM = 'UPDATE_CURRENT_FORUM'

// discussion
export const START_FETCHING_DISCUSSIONS = 'START_FETCHING_DISCUSSIONS'
export const FETCHING_DISCUSSIONS_SUCCESS = 'FETCHING_DISCUSSIONS_SUCCESS'
export const FETCHING_DISCUSSIONS_FAILURE = 'FETCHING_DISCUSSIONS_FAILURE'
// pind discussion
export const START_FETCHING_PINED_DISCUSSIONS = 'START_FETCHING_PINED_DISCUSSIONS'
export const FETCHING_PINED_DISCUSSIONS_SUCCESS = 'FETCHING_PINED_DISCUSSIONS_SUCCESS'
export const FETCHING_PINED_DISCUSSIONS_FAILURE = 'FETCHING_PINED_DISCUSSIONS_FAILURE'

export const UPDATE_SORTING_METHOD = 'UPDATE_SORTING_METHOD'
export const INVALID_FORUM = 'INVALID_FORUM'

// discussion detail
export const FETCHING_DISCUSSIONS_DETAIL_START = 'FETCHING_DISCUSSIONS_DETAIL_START'
export const FETCHING_DISCUSSIONS_DETAIL_SUCCESS = 'FETCHING_DISCUSSIONS_DETAIL_SUCCESS'
export const FETCHING_DISCUSSIONS_DETAIL_FAILURE = 'FETCHING_DISCUSSIONS_DETAIL_FAILURE'

export const TOGGLE_FAVORITE_START = 'TOGGLE_FAVORITE_START'
export const TOGGLE_FAVORITE_SUCCESS = 'TOGGLE_FAVORITE_SUCCESS'
export const TOGGLE_FAVORITE_FAILURE = 'TOGGLE_FAVORITE_FAILURE'

export const UPDATE_OPINION_CONTENT = 'UPDATE_OPINION_CONTENT'

export const POSTING_OPINION_START = 'POSTING_OPINION_START'
export const POSTING_OPINION_SUCCESS = 'POSTING_OPINION_SUCCESS'
export const POSTING_OPINION_FAILURE = 'POSTING_OPINION_FAILURE'

export const DELETE_DISCUSSION_START = 'DELETE_DISCUSSION_START'
export const DELETE_DISCUSSION_SUCCESS = 'DELETE_DISCUSSION_SUCCESS'
export const DELETE_DISCUSSION_FAILURE = 'DELETE_DISCUSSION_FAILURE'
export const DELETE_DISCUSSION_REDIRECT = 'DELETE_DISCUSSION_REDIRECT'

export const DELETE_OPINION_START = 'DELETE_OPINION_START'
export const DELETE_OPINION_FAILURE = 'DELETE_OPINION_FAILURE'
export const DELETE_OPINION_SUCCESS = 'DELETE_OPINION_SUCCESS'